// Emulator seeding for the x-e2e-happy-path suite. Adapts (does not edit —
// scripts/seed.mjs is off-limits, "invoke it, do not edit") the Admin-SDK
// seed script's own payload builders so the Event + prompt pool this suite
// deals boards from is byte-identical in shape to what a real operator seed
// would write. `firebase-admin` is deliberately NOT an app/e2e dependency
// (see scripts/seed.mjs's own header comment), so this uses the
// `@firebase/rules-unit-testing` devDependency the tests/rules/ layer already
// relies on — its `withSecurityRulesDisabled` context is the same
// rules-bypassing write path an Admin SDK gets, without adding a dependency.
import { initializeTestEnvironment, type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { doc, deleteField, getDoc, writeBatch } from 'firebase/firestore';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
// @ts-expect-error — scripts/seed.mjs is a plain-JS node script with no type
// declarations (tsconfig sets no allowJs, and only includes src/ besides).
// It is side-effect-free to import: seeding only runs when the script is the
// entry module (see its own `import.meta.url === ...` guard). Mirrors the
// same import src/test/w1-event-seed.test.ts already uses against Vitest.
import { EVENT_SEED, ITEMS, adminRoster, eventWritePayload, seedItemDocId } from '../../../scripts/seed.mjs';
import { EVENT_ID, FIRESTORE_HOST, FIRESTORE_PORT, PROJECT_ID } from './env';

const RULES_PATH = fileURLToPath(new URL('../../../firestore.rules', import.meta.url));

/**
 * A dense pool needs >= MIN_POOL (24, src/game/logic.ts) active, non-free
 * Prompts so `dealBoard` never throws (ADR 0004 guard). scripts/seed.mjs's
 * own ITEMS list is reused verbatim rather than re-declaring a parallel
 * fixture, so this suite seeds the exact real pool shape.
 */
export const SEEDED_ACTIVE_PROMPT_COUNT = ITEMS.length;

/**
 * Boots a rules-test environment against the already-running Firestore
 * emulator (started by `firebase emulators:exec` under `npm run test:e2e`),
 * CLEARS it, and writes the Event doc + full ITEMS pool with security rules
 * disabled — the same rules-bypassing posture `scripts/seed.mjs` gets from
 * the Admin SDK. Caller owns `testEnv.cleanup()`.
 */
export async function seedEmulatorEvent(): Promise<RulesTestEnvironment> {
  const testEnv = await initializeTestEnvironment({
    projectId: PROJECT_ID,
    firestore: {
      host: FIRESTORE_HOST,
      port: FIRESTORE_PORT,
      rules: readFileSync(RULES_PATH, 'utf8'),
    },
  });

  // Every attempt starts from a clean slate (Codex P2 on PR #114 round 2; the
  // tests/rules suites' own beforeEach pattern): the suite's afterAll only
  // cleanup()s the test env, so players/boards rows from a FAILED attempt would
  // otherwise persist in the same `emulators:exec` process — and a Playwright
  // CI retry (fresh worker, so beforeAll re-runs this seed) would join a
  // SECOND generated user, making the happy-path case's sole-Player rows
  // assertion permanently unrecoverable. The AUTH emulator does accumulate one
  // autogenerated account per join attempt, and that is deliberately left
  // alone: no assertion counts auth users — the board observer is uid-scoped
  // (boardHasMarkedText) and the leaderboard count reads the Firestore players
  // rows this wipe just reset — so auth accumulation is harmless.
  await testEnv.clearFirestore();

  await testEnv.withSecurityRulesDisabled(async (context) => {
    const db = context.firestore();
    const eventRef = doc(db, 'events', EVENT_ID);
    const batch = writeBatch(db);
    // No ADMIN_UID roster: this ticket asserts the zero-admin-action path, so
    // the seed intentionally leaves `admins` empty (eventWritePayload omits
    // the key entirely — see scripts/seed.mjs).
    batch.set(eventRef, eventWritePayload(adminRoster(''), deleteField()), {
      merge: true,
    });
    const now = Date.now();
    for (const { text, spicy } of ITEMS) {
      const itemRef = doc(db, 'events', EVENT_ID, 'items', seedItemDocId(text));
      batch.set(
        itemRef,
        {
          text,
          createdBy: 'seed',
          createdAt: now,
          isFreeSpace: false,
          status: 'active',
          reportCount: 0,
          spicy,
        },
        { merge: true },
      );
    }
    await batch.commit();
  });

  return testEnv;
}

/**
 * Ground truth for the ADR 0006 sync assertion: reads THIS Player's board doc
 * (`events/{EVENT_ID}/boards/{uid}` — boards are keyed by uid, see
 * src/data/paths.ts `boardRef`) straight from the emulator, rules disabled,
 * and reports whether that board has `text` marked. Scoped to the signed-in
 * uid on purpose (Codex P2 on PR #114): both cases join the same shared Event,
 * so an any-board scan could false-pass on a prompt-text collision with the
 * happy-path Player's already-marked board — uid-scoping makes the assertion
 * provably about the offline Mark this case just made. An INDEPENDENT read
 * path from the page under test — never the reloaded tab's own cache —
 * mirrors the observer pattern in tests/offline/w0-offline-persistence.test.ts.
 */
export async function boardHasMarkedText(
  testEnv: RulesTestEnvironment,
  uid: string,
  text: string,
): Promise<boolean> {
  // `withSecurityRulesDisabled` is typed `(cb) => Promise<void>` and DISCARDS the
  // callback's return value, so the result must be captured in this outer scope
  // — `return testEnv.withSecurityRulesDisabled(async () => …)` would always
  // resolve to `undefined`. (tsconfig typechecks only src/, so tsc never flags
  // it, and Playwright strips types without checking.)
  let found = false;
  await testEnv.withSecurityRulesDisabled(async (context) => {
    const db = context.firestore();
    const snap = await getDoc(doc(db, 'events', EVENT_ID, 'boards', uid));
    const cells =
      (snap.data() as { cells?: Array<{ text: string; marked: boolean }> } | undefined)?.cells ?? [];
    found = cells.some((c) => c.text === text && c.marked === true);
  });
  return found;
}

/**
 * Whether `users/{uid}` carries a persisted 18+ attestation (`attestedAdultAt`,
 * #23/#112) in the emulator. The offline case polls this BEFORE cutting the
 * network: `signIn()` persists the attestation via `attestAdult` — a Firestore
 * TRANSACTION, which needs the network and never queues offline — *after* the
 * popup resolves, and the signed-in shell renders before that transaction
 * commits. Going offline too early kills it mid-flight (the offline reload then
 * discards it — transactions are not part of the durable mutation queue),
 * leaving the User permanently un-attested, so the post-sync reload would land
 * on the #23 re-prompt gate instead of the Board. Waiting for the attestation
 * to be server-visible pins "the join fully settled" before the dead zone
 * starts — which is also the realistic ordering for a Player who joined online.
 */
export async function userAttested(testEnv: RulesTestEnvironment, uid: string): Promise<boolean> {
  // Result captured in the outer scope — withSecurityRulesDisabled discards the
  // callback's return value (see boardHasMarkedText above).
  let attested = false;
  await testEnv.withSecurityRulesDisabled(async (context) => {
    const db = context.firestore();
    const snap = await getDoc(doc(db, 'users', uid));
    attested =
      typeof (snap.data() as { attestedAdultAt?: unknown } | undefined)?.attestedAdultAt === 'number';
  });
  return attested;
}

// Re-exported so the spec can assert the payload it just wrote matches the
// real operator seed (name, claimMode, etc.) without re-importing seed.mjs.
export { EVENT_SEED };
