// Phase 1.5 verification — chrome-finale sweep, area 1: the Tab bar contract
// (Card · Feed · Ranks · More) and the More menu's row-by-row contents
// (daily-cards-spec § "More menu", specs/d15-tab-contract.md, #208).
// Drives the real app + Firebase emulators against a full 5-Day seed
// (embark / two main / farewell / locked) so every reachable More row has a
// live Event doc behind it.
import { test, expect } from '@playwright/test';
import { doc, updateDoc, setDoc } from 'firebase/firestore';
import type { RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { seedDailyEvent, dismissCoach } from './support/daily';
import { joinViaSharedLink, signedInUid } from './support/join';
import { waitForBoardServerConfirmed } from './support/board';
import { EVENT_ID } from './support/env';

const SHOTS = process.env.E2E_SHOT_DIR || 'test-results/shots';

test.describe('tab bar + More menu', () => {
  let testEnv: RulesTestEnvironment;

  test.beforeAll(async () => {
    ({ testEnv } = await seedDailyEvent());
  });
  test.afterAll(async () => {
    await testEnv?.cleanup();
  });

  test('tab bar is Card · Feed · Ranks · More, in that order, with Lucide glyphs + a More fallback icon', async ({
    page,
  }) => {
    await joinViaSharedLink(page);
    await waitForBoardServerConfirmed(page);
    await dismissCoach(page);

    const nav = page.getByRole('navigation', { name: 'Primary' });
    // Card / Feed / Ranks carry a Lucide <svg class="tab-icon">; More wears
    // either the Player's avatar <img class="tab-avatar"> or the `ellipsis`
    // fallback <svg class="tab-ellipsis"> — the emulator's autogenerated
    // sign-in identity carries no photoURL, so the fallback path is what a
    // real run against this stack exercises.
    const cardTab = nav.getByRole('link', { name: 'Card' });
    const feedTab = nav.getByRole('link', { name: 'Feed' });
    const ranksTab = nav.getByRole('link', { name: 'Ranks' });
    const moreTab = nav.getByRole('link', { name: 'More' });
    await expect(cardTab).toBeVisible();
    await expect(feedTab).toBeVisible();
    await expect(ranksTab).toBeVisible();
    await expect(moreTab).toBeVisible();
    // DOM order: Card, Feed, Ranks, More (the frozen tabs.ts array order).
    const order = await nav.getByRole('link').evaluateAll((els) => els.map((el) => el.getAttribute('aria-label') || el.textContent?.trim()));
    expect(order).toEqual(['Card', 'Feed', 'Ranks', 'More']);

    await expect(cardTab.locator('svg.tab-icon')).toHaveCount(1);
    await expect(feedTab.locator('svg.tab-icon')).toHaveCount(1);
    await expect(ranksTab.locator('svg.tab-icon')).toHaveCount(1);
    // More: no photoURL on the emulator identity → ellipsis fallback, not the avatar.
    await expect(moreTab.locator('svg.tab-ellipsis')).toHaveCount(1);
    await expect(moreTab.locator('img.tab-avatar')).toHaveCount(0);
    await page.screenshot({ path: `${SHOTS}/tab-bar.png`, fullPage: true });
  });

  test('More menu: profile, theme, text size, play rows, support rows, sign out, version footer — in order, no Admin row for a non-admin', async ({
    page,
  }) => {
    await joinViaSharedLink(page);
    await waitForBoardServerConfirmed(page);
    await dismissCoach(page);

    await page.getByRole('link', { name: 'More' }).click();

    // 1. Profile card — avatar/name/@handle trigger.
    const profileRow = page.getByRole('button', { name: 'Edit profile' });
    await expect(profileRow).toBeVisible();

    // 2. Theme — Auto is the leading, active-by-default chip.
    const themeGroup = page.locator('.themes[aria-label="Theme"]');
    const autoChip = themeGroup.getByRole('button', { name: /Auto — match the day/ });
    await expect(autoChip).toBeVisible();
    await expect(autoChip).toHaveClass(/active/);
    // Picking a concrete theme overrides Auto; App's <html data-theme> follows it.
    const partyChip = themeGroup.getByRole('button').nth(1);
    await partyChip.click();
    await expect(partyChip).toHaveClass(/active/);
    await expect(autoChip).not.toHaveClass(/active/);
    await expect(page.locator('html')).not.toHaveAttribute('data-theme', 'auto');
    // Restore Auto so later assertions (and other tests reusing this Player)
    // aren't left on a manually-pinned theme.
    await autoChip.click();
    await expect(autoChip).toHaveClass(/active/);

    // 2.5 Text size — S/M/L segmented control, Medium selected by default.
    const textSizeGroup = page.getByRole('group', { name: 'Text size' });
    await expect(textSizeGroup.getByRole('button', { name: 'Medium' })).toHaveAttribute('aria-pressed', 'true');
    await textSizeGroup.getByRole('button', { name: 'Large' }).click();
    await expect(textSizeGroup.getByRole('button', { name: 'Large' })).toHaveAttribute('aria-pressed', 'true');
    await expect(page.locator('html')).toHaveAttribute('data-text-size', 'large');

    // 3. Play section — schedule / suggest / how-to-play rows (install row is
    // conditional on installability signals, covered by the PWA spec).
    await expect(page.getByRole('button', { name: /Cruise schedule/ })).toBeVisible();
    await expect(page.getByRole('button', { name: /Suggest a square/ })).toBeVisible();
    await expect(page.getByRole('button', { name: /How to play/ })).toBeVisible();

    // 5. Support — bug report + 18+ / acceptable-use guidelines. AcceptableUse's
    // `variant="row"` (the only variant More.tsx mounts — see AcceptableUse.tsx)
    // titles the row "18+ advisory & acceptable use", not the floating variant's
    // plain "Guidelines" label.
    await expect(page.getByRole('button', { name: 'Report a bug' })).toBeVisible();
    await expect(page.getByRole('button', { name: /18\+ advisory & acceptable use/ })).toBeVisible();

    // 6. NO Admin row for a non-admin Player.
    await expect(page.getByRole('button', { name: /^Admin/ })).toHaveCount(0);

    // 7. Sign out — present, last-but-one.
    await expect(page.getByRole('button', { name: 'Sign out' })).toBeVisible();

    // 8. Version footer.
    await expect(page.locator('.more-version')).toContainText(/^v/);
    await page.screenshot({ path: `${SHOTS}/more-menu.png`, fullPage: true });
  });

  test('Report a bug can capture a different screen than More (#324)', async ({ page }) => {
    await joinViaSharedLink(page);
    await waitForBoardServerConfirmed(page);
    await dismissCoach(page);
    await page.getByRole('link', { name: 'More' }).click();
    await page.getByRole('button', { name: 'Report a bug' }).click();

    const dialog = page.getByRole('dialog', { name: 'Report a bug' });
    await expect(dialog).toBeVisible();
    // The on-open capture (of /more) lands, proving real html-to-image works
    // in this stack before pick mode swaps it out.
    await expect(
      dialog.getByRole('img', { name: 'Screenshot that will be submitted with this bug report' }),
    ).toBeVisible();
    await dialog.getByLabel('What happened?').fill('A tile on my card is broken.');
    await dialog.getByRole('button', { name: 'Capture a different screen' }).click();
    await expect(dialog).toHaveCount(0);

    // The sheet is parked: the tab bar stays usable behind the pick bar, and
    // leaving /more unmounts the only launcher — the regression #324 fixed.
    await page.getByRole('link', { name: 'Card' }).click();
    await expect(page.getByRole('button', { name: 'Report a bug' })).toHaveCount(0);
    await page.screenshot({ path: `${SHOTS}/bug-report-pick-mode.png`, fullPage: true });
    await page.getByRole('button', { name: 'Capture this screen' }).click();

    // The sheet reopens over Card with the fresh capture and the draft intact.
    await expect(page.getByRole('dialog', { name: 'Report a bug' })).toBeVisible();
    await expect(
      page.getByRole('img', { name: 'Screenshot that will be submitted with this bug report' }),
    ).toBeVisible();
    await expect(page.getByLabel('What happened?')).toHaveValue('A tile on my card is broken.');
    await page.screenshot({ path: `${SHOTS}/bug-report-pick-captured.png`, fullPage: true });
    // No submit here: the callable's functions emulator isn't part of this
    // stack; submission stays covered by the component + functions suites.
    await page.getByRole('button', { name: 'Cancel' }).click();
    await expect(page.getByRole('dialog', { name: 'Report a bug' })).toHaveCount(0);
  });

  test('Cruise schedule row opens a read-only list of every seeded Day', async ({ page }) => {
    await joinViaSharedLink(page);
    await waitForBoardServerConfirmed(page);
    await dismissCoach(page);
    await page.getByRole('link', { name: 'More' }).click();
    await page.getByRole('button', { name: /Cruise schedule/ }).click();

    await expect(page.getByRole('dialog', { name: 'Cruise schedule' })).toBeVisible();
    // 5 seeded Days (support/daily.ts) each render a row with port + theme + unlock time.
    await expect(page.locator('.sheet.more-panel .list .row')).toHaveCount(5);
    await page.screenshot({ path: `${SHOTS}/more-schedule.png`, fullPage: true });
    await page.getByRole('button', { name: 'Close' }).click();
    await expect(page.getByRole('dialog', { name: 'Cruise schedule' })).toHaveCount(0);
  });

  test('Suggest a square row opens the ItemPool add bar and a submission lands', async ({ page }) => {
    await joinViaSharedLink(page);
    await waitForBoardServerConfirmed(page);
    await dismissCoach(page);
    await page.getByRole('link', { name: 'More' }).click();
    await page.getByRole('button', { name: /Suggest a square/ }).click();
    await expect(page.getByRole('dialog', { name: 'Suggest a square' })).toBeVisible();
    await expect(page.getByPlaceholder('Add a prompt…')).toBeVisible();
    await page.screenshot({ path: `${SHOTS}/more-suggest.png`, fullPage: true });
  });

  test('an admin sees the Admin row badged with the pending-approvals count', async ({ page }) => {
    const { testEnv: env } = await seedDailyEvent();
    try {
      await joinViaSharedLink(page);
      const uid = await signedInUid(page);
      await waitForBoardServerConfirmed(page);
      await dismissCoach(page);

      // Promote to admin AND seed one pending prompt so the badge has a count.
      await env.withSecurityRulesDisabled(async (ctx) => {
        await updateDoc(doc(ctx.firestore(), 'events', EVENT_ID), { admins: [uid] });
        await setDoc(doc(ctx.firestore(), 'events', EVENT_ID, 'items', 'e2e-pending-item'), {
          text: 'E2E pending item',
          createdBy: 'someone-else',
          createdAt: Date.now(),
          isFreeSpace: false,
          status: 'pending',
          reportCount: 0,
          spicy: false,
        });
      });

      await page.getByRole('link', { name: 'More' }).click();
      const adminRow = page.getByRole('button', { name: /^Admin/ });
      await expect(adminRow).toBeVisible({ timeout: 10_000 });
      await expect(adminRow.locator('.more-badge')).toHaveText('1');
      await page.screenshot({ path: `${SHOTS}/more-admin-row-badged.png`, fullPage: true });
    } finally {
      await env.cleanup();
    }
  });
});
